name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            linux-musl,
#            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/chopper
            asset_name: chopper-linux
          - name: linux-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: target/x86_64-unknown-linux-musl/release/chopper
            asset_name: chopper-linux-musl
#          - name: windows
#            os: windows-latest
#            artifact_name: target/release/<name>.exe
#            asset_name: <name>-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/chopper
            asset_name: chopper-macos

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Install musl tools
      if: matrix.name == 'linux-musl'
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release ${{ matrix.target && format('--target {0}', matrix.target) || '' }} --locked

    - name: Upload binaries to release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}